ktor:
  application:
    modules:
      - nrs.sankarsana.bookstore.ApplicationKt.module
  deployment:
    port: 8080

services:
  db:
    environment:
      URL: "jdbc:postgresql://localhost:5432/books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "books"