openapi: 3.0.1
info:
  title: Book Store API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Получение отсутсвующий базы
      parameters:
        - name: database_version
          in: header
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful